#include <math.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define MAX_NUMBER (int)(1e6)

typedef struct {
  uint32_t product;
  uint32_t exp;
} Prime_Product;

typedef struct {
  Prime_Product *products;
  size_t size;
  size_t capacity;
} Prime_Product_Holder;

void answer1(int num);
void answer2(Prime_Product_Holder *holder, uint32_t num);
void add_product(Prime_Product_Holder *holder, Prime_Product new_product);
void calculate_primes(void);
int number;

bool primes[MAX_NUMBER + 1]; // if primes[i] true : prime else : not prime

int main(void) {

  memset(&primes, 0, sizeof(primes));
  double sonuc = sqrt(123);
  calculate_primes();

  printf("Bir sayi giriniz : ");
  scanf("%d", &number);
  //************** 1. yontem  ****************//
  answer1(number);

  //************** 2. yontem  ****************//
  Prime_Product_Holder holder = {.size = 0, .capacity = 0};
  printf("Products generated by answer 2 : ");

  answer2(&holder, number);
  for (int i = 0; i < holder.size; i++) {
    printf("\n%d ^ %d", holder.products[i].product, holder.products[i].exp);
  }

  free(holder.products);
}

void calculate_primes(void) {

  bool mask[MAX_NUMBER + 1];
  memset(&mask, 0, sizeof(mask));

  for (int p = 2; p < MAX_NUMBER; p++) {
    if (mask[p] == false) {

      primes[p] = true;

      if (p <= MAX_NUMBER / p) {
        for (int c = p * p; c <= MAX_NUMBER; c += p) {
          mask[c] = true;
        }
      }
    }
  }
}

void answer1(int num) {
  int count_products = 0;

  uint32_t center = (int)sqrt(num) + 1;

  printf("Products of %d that generated by answer1 :\n", num);

  for (int product = 1; product < center; product++) {
    if (num % product == 0) {
      printf("  %d  x  %d\n", product, num / product);
    }
  }
}

void answer2(Prime_Product_Holder *holder, uint32_t num) {
  uint32_t temp = num;
  uint32_t center = (int)sqrt(num) + 2;

  for (int i = 2; temp != 1; i++) {
    if (primes[i] == true) {

      uint32_t counter = 0;

      while (temp % i == 0) {
        counter++;
        temp /= i;
        printf("\ntemp : %d", temp);
      }

      if (counter > 0) {
        Prime_Product newProduct = {.exp = counter, .product = i};
        add_product(holder, newProduct);
      }
    }
  }
}

void add_product(Prime_Product_Holder *holder, Prime_Product new_product) {

  if (holder->size == holder->capacity) {
    size_t newcapacity = (holder->capacity == 0) ? 4 : holder->capacity * 2;

    Prime_Product *temp =
        realloc(holder->products, newcapacity * sizeof(Prime_Product));

    if (temp == NULL) {
      printf("Bellek alani yetersiz.");
      return;
    }

    holder->products = temp;
    holder->capacity = newcapacity;
  }
  printf("\nnew product  added");
  holder->products[holder->size] = new_product;
  holder->size++;
}
